- name: Build And Deploy
        id: swa
        uses: azure/static-web-apps-deploy@latest
        with:
          azure_static_web_apps_api_token: ${{ 2e524621c423b25bafd993cbc58db3dd9d92198ddc072adde10408bf895c57b72-ade3f159-77c7-478d-bc57-5dfea8c22823010172428 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for GitHub integrations (i.e. PR comments)
          action: "upload"
          app_location: "/" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "" # Built app content directory - optional
        env: # Add environment variables here
          is_static_export: true
